package matms.domain;

public enum MartialArt {
	AIKIDO, BOX, JIU_JITSU, CAPOEIRA, FENCING, HAPKIDO, JEET_KUNE_DO, JUDO, KARATE, KENDO, KICKBOXING, KRAV_MAGA,
	LUTA_LIVRE, MUAY_THAI, WRESTLING, SYSTEMA, TAEKWONDO, WING_CHUN, VALE_TUDO, MMA, KUNG_FU, NINJUTSU
}
